import logging

from django.core.management.base import BaseCommand

from account.repository.generator_layer import AccountDataGenerator

logger = logging.getLogger(__name__)
DGL = AccountDataGenerator()


class Command(BaseCommand):
    """Data Generator

    Generate data for Account app. It is usable
    for automatic and manual tests.
    """
    help = 'Generate data for Basket'

    def add_arguments(self, parser):
        parser.add_argument('--total-users',
                            type=int,
                            default=300,
                            help='Specify number of users to generate.'
                            )

    def handle(self, *args, **kwargs):
        total_users = kwargs['total_users']
        self.stdout.write(self.style.WARNING('Prepare to generate data...'))

        DGL.create_user(total_users)
        self.stdout.write(self.style.HTTP_NOT_MODIFIED(
            f'{total_users} Users have been generated by machine.')
        )
        DGL.create_profile()
        self.stdout.write(self.style.HTTP_NOT_MODIFIED(
            f'{total_users} Profiles have been generated by machine.')
        )
        self.stdout.write(self.style.SUCCESS('Data Generation finished'))
